### ISSUE TITLE
Error using AlphaFold models

### ISSUE THREAD

**Issue by noamkatz1** [jozhang97/MutateEverything#6]
Hello,
I am having a trouble when loading the MutateEverything af model.
it seems like there are some mismatches between the given weights and the definition of the model in the code.
Traceback (most recent call last):
  File "/root/capsule/code/MutateEverything-master/test.py", line 179, in <module>
    main(args)
  File "/root/capsule/code/MutateEverything-master/test.py", line 102, in main
    misc.load_model(args, model, None, None)
  File "/root/capsule/code/MutateEverything-master/misc.py", line 385, in load_model
    model_without_ddp.load_state_dict(checkpoint['model'])
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MutateEverything:
	Unexpected key(s) in state_dict: "backbone.bb_adapter1.linear1.weight", "backbone.bb_adapter1.linear1.bias", "backbone.bb_adapter1.linear2.weight", "backbone.bb_adapter1.linear2.bias", "backbone.bb_adapter1.norm.weight", "backbone.bb_adapter1.norm.bias". 

I would Highly appreciate your guidance and help! Thx!

**Comment by jozhang97** [comment]
Hi,

What is the exact command you ran? I suspect that an argument may be different.
