### ISSUE TITLE
Error using af backbone

### ISSUE THREAD

**Issue by daiheng-zhang** [jozhang97/MutateEverything#7]
Hi Jeffrey,

I encountered an issue while using the af backbone for evaluation. First, I followed the readme to install environment.yml, flash-attention, and openfold. Here is where I ran into problems: `ImportError: cannot import name 'resources' from 'openfold'`. Then I add the `openfold/data`, `openfold/resources` and reinstall the openfold. The new issue is 
```
Start testing
Traceback (most recent call last):
  File "test.py", line 179, in <module>
    main(args)
  File "test.py", line 112, in main
    pred = forward_af(model, args)
  File "/ai/sharedisk/workspace/daiheng/mutate_everything/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "test.py", line 63, in forward_af
    from openfold.data import feature_pipeline, data_pipeline
  File "/ai/sharedisk/workspace/daiheng/mutate_everything/lib/python3.7/site-packages/openfold-1.0.1-py3.7-linux-x86_64.egg/openfold/data/data_pipeline.py", line 26, in <module>
    from openfold.data import templates, parsers, mmcif_parsing, msa_identifiers, msa_pairing, feature_processing_multimer
  File "/ai/sharedisk/workspace/daiheng/mutate_everything/lib/python3.7/site-packages/openfold-1.0.1-py3.7-linux-x86_64.egg/openfold/data/templates.py", line 30, in <module>
    from openfold.data import parsers, mmcif_parsing
  File "/ai/sharedisk/workspace/daiheng/mutate_everything/lib/python3.7/site-packages/openfold-1.0.1-py3.7-linux-x86_64.egg/openfold/data/mmcif_parsing.py", line 27, in <module>
    from Bio.Data import PDBData
ImportError: cannot import name 'PDBData' from 'Bio.Data' (/ai/sharedisk/workspace/daiheng/mutate_everything/lib/python3.7/site-packages/Bio/Data/__init__.py)
```
I tried different versions of Biopython, but none were successful. Do you have any suggestions? My running command is:
`python test.py  --backbone af  --finetune_backbone models/finetuning_2.pt  --resume models/mutate_everything_af.pth  --output_dir example/1gl5_af  --name 1gl5  --seq example/1gl5.fasta  --msa_dir example/1gl5_msa`

**Comment by jozhang97** [comment]
Hi Daiheng, 

Are you still facing this issue? I've never seen this issue before, I would try maybe a clean installation from scratch.

**Comment by jozhang97** [comment]
It could be a different openfold/data, you can try using the one that I just uploaded to the repo.

**Comment by daiheng-zhang** [comment]
Thank you for your help. I wanted to let you know that it is working now.
